/* =====================================================================
   save-frames.mjs
   Stores EIS rep still frames in Netlify Blobs.

   DEPLOY
     Put this file in:  netlify/functions/save-frames.mjs
     Also add the package.json in this folder to your site root (or
     merge the dependency in if you already have one).
     No environment variables. No provisioning. Blobs is zero-config
     on Netlify.

   CALLED AFTER the report saves, never before. If this fails the
   report is already in the database and nothing is lost.

   SIZE MATH
     ~35KB per frame, 15 reps per prospect, 100 prospects = ~52MB.
===================================================================== */

import { getStore } from "@netlify/blobs";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Content-Type": "application/json",
};

/* Keys are generated by the client as rep_<timestamp>. Validate hard.
   Never let a caller hand us an arbitrary key. */
const KEY_OK = /^rep_[0-9]{10,20}$/;
const MAX_FRAME_BYTES = 400_000;
const MAX_FRAMES_PER_CALL = 40;

export default async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  if (req.method !== "POST")
    return new Response(JSON.stringify({ error: "POST only" }), { status: 405, headers: CORS });

  let body;
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Bad JSON" }), { status: 400, headers: CORS });
  }

  const frames = Array.isArray(body.frames) ? body.frames.slice(0, MAX_FRAMES_PER_CALL) : [];
  if (!frames.length)
    return new Response(JSON.stringify({ success: true, saved: [], skipped: 0 }), { headers: CORS });

  const store = getStore("eis-frames");
  const saved = [];
  const skipped = [];

  for (const f of frames) {
    const key = String(f?.key || "");
    if (!KEY_OK.test(key)) { skipped.push({ key, why: "bad key" }); continue; }

    const m = /^data:image\/(jpeg|jpg|png);base64,([A-Za-z0-9+/=]+)$/.exec(String(f?.dataUrl || ""));
    if (!m) { skipped.push({ key, why: "not an image data url" }); continue; }

    let buf;
    try { buf = Buffer.from(m[2], "base64"); }
    catch { skipped.push({ key, why: "decode failed" }); continue; }

    if (!buf.length || buf.length > MAX_FRAME_BYTES) {
      skipped.push({ key, why: "size " + buf.length });
      continue;
    }

    try {
      await store.set(key, buf, {
        metadata: {
          contentType: m[1] === "png" ? "image/png" : "image/jpeg",
          prospect: String(body.prospect || "").slice(0, 120),
          reportId: String(body.reportId || "").slice(0, 60),
          storedAt: new Date().toISOString(),
        },
      });
      saved.push(key);
    } catch (err) {
      skipped.push({ key, why: String(err.message || err) });
    }
  }

  return new Response(JSON.stringify({ success: true, saved, skipped }), { headers: CORS });
};
